# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_code', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
