# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toggler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_code', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FanSpeed',
            fields=[
                ('toggler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='control.Toggler')),
            ],
            bases=('control.toggler',),
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('toggler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='control.Toggler')),
            ],
            bases=('control.toggler',),
        ),
    ]
